version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    hubot:
# build arguments, only needed for building
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: hubot
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
                HUBOT_USER: hubot
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.12.4}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: hubot
                version.cbf: $CBF_VERSION
        container_name: hubot
        environment:
# common arguments, for building and deploy 
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            HUBOT_BOT_NAME: hubot
#            HUBOT_GITHUB_REPOS_MAP: '{"git":[""devops/hubot_container","devops/jenkins_container","devops/nagios_container","devops/nginx-base_container"]}'
#            HUBOT_GITHUB_TOKEN_FILE: /run/secrets/github.token
#            HUBOT_GITHUB_WEBHOOK_SECRET_FILE: /run/secrets/hubot_github_webhook_secret
            HUBOT_SLACK_TOKEN_FILE: /run/secrets/slack.token
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
        hostname: hubot
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/hubot:${CONTAINER_TAG:-latest}
# deploy arguments, not needed for building
        logging:                              # limit size of logs @runtime so that we do not run out of space 
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:                                #ports exposed 
            - "5858:5858"
            - "8081:8080"
            - "8123:8123"
        restart: unless-stopped               # only use when building a 'service container'
# references to 'secrets' section below
            - supervisord.pwd
            - slack.token
        volumes:
            - ./vols/redis:/var/lib/redis
            - ./vols/conf:/opt/hubot
# application logs
            - ./vols/log:/var/log

secrets:
# location of secrets files in host filesystem
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
   github.token:
     file: ~/.inf/secrets/hubot_token.github
   slack.token:
     file: ~/.inf/secrets/hubot_token.slack
